credentials:
  usernames:
    user1:
      name: user1
      password: user1@123
    user2:
      name: user2
      password: user2@123
cookie:
  expiry_days: 30
  key: authentication_key
  name: authentication
preauthorized:
  emails:
    - users@gmail.com